version: "3.3"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
    - ./nginxconf:/etc/nginx/conf.d 
    networks:
    - all  
    depends_on:
      - visby-account
      - visby-papers
      - visby-professors
      - visby-user-profile

  visby-account:
    build:
      context: "."
      dockerfile: "./account.Dockerfile"
    ports:
      - 6655:80
    depends_on:
      - account-db
    networks:
      - all

  account-db:
    image: postgres:12
    volumes:
      - account-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 54321:5432
    networks:
      - all

  visby-papers:
    build:
      context: "."
      dockerfile: "./papers.Dockerfile"
    ports:
      - 6656:80
    #  depends_on:
    #   - papers-db
    networks:
      - all

  papers-db:
    build:
      context: "."
      dockerfile: "./pgsql-jieba.Dockerfile"
    # volumes:
    #   - papers-db-volume:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 54322:5432
    networks:
      - all

  visby-professors:
    build:
      context: "."
      dockerfile: "./professors.Dockerfile"
    ports:
      - 6657:80
    depends_on:
      - professors-db
    networks:
      - all
    environment:
      - PaperContext="Host=visby_professors-db_1;Username=postgres;Password=postgres;Database=account"

  professors-db:
    image: postgres:12
    volumes:
      - papers-db-volume:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 54323:5432
    networks:
      - all

  visby-user-profile:
    build:
      context: "."
      dockerfile: "./user-profile.Dockerfile"
    ports:
      - 6658:80
    depends_on:
      - user-profile-db
    networks:
      - all
    environment:
      - PaperContext="Host=visby_user-profile-db_1;Username=postgres;Password=postgres;Database=account"

  user-profile-db:
    image: postgres:12
    volumes:
      - user-profile-db-volume:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 54324:5432
    networks:
      - all

volumes:
  account-db-volume:
  papers-db-volume:
  professors-db-volume:
  user-profile-db-volume:

networks:
  all:
